name: milk

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send 5 milk webhooks
        run: |
          for i in {1..5}
          do
            curl -X POST -H "Content-Type: application/json" \
            -d '{"content":"https://tenor.com/view/glass-of-milk-milk-pour-some-milk-gimme-some-milk-beautylicious-gif-16611440"}' \
            ${{ secrets.WEBHOOK_URL }}

            sleep 1
          done
